version: '3.6'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12323787fd87df87df87df873445fff  
      POSTGRES_DB: test
    # network_mode: "host"
    
    ports:
      - "127.0.0.1:52492:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  serial:
    image: m00nl1g7/serial    
      #image: serial    
    environment:
      - API_KEY=${API_KEY}
      - API_KEY_LIFETIME=${API_KEY_LIFETIME}
    depends_on:
      - postgres
    network_mode: host

volumes:
  postgres_data:
    driver: local
    