version: '3.6'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: test
    # network_mode: "host"
    
    ports:
      - "127.0.0.1:5432:5432"
    # networks:
    #   - wild_west

  serial:
    image: m00nl1g7/serial    
    environment:
      - API_KEY=${API_KEY}
      - API_KEY_LIFETIME=${API_KEY_LIFETIME}
    depends_on:
      - postgres
    network_mode: "host"
    
    # network_mode: "host"  # Add this line to use host network
    # networks:
    #   - wild_east
    #   - wild_west

# networks:
#   wild_west:
#     driver: bridge
#   wild_east:
#     driver: host

