---
- name: Change password for individual user on remote host
  hosts: all
  vars:
    username: "{{ username }}"
    new_password: "{{ new_password }}"

  tasks:
    - name: Set password for the user
      user:
        name: "{{ username }}"
        password: "{{ new_password | password_hash('sha512') }}"
        update_password: always