---
- name: Change password for all non-system users on remote host
  hosts: all
  vars:
    new_password: "{{ new_password }}"
    system_uid_threshold: 1000

  tasks:
    - name: Get list of users with shells
      command: getent passwd
      register: passwd_output

    - name: Set password for each user
      user:
        name: "{{ item.split(':')[0] }}"
        password: "{{ new_password | password_hash('sha512') }}"
        update_password: always
      loop: "{{ passwd_output.stdout_lines }}"
      when: item.split(':')[0] != 'root' and item.split(':')[2] | int >= system_uid_threshold