---
- name: List Installed Software
  hosts: all
  gather_facts: false
  tasks:
    - name: PS command to list installed software
      win_shell: Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*, HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Where-Object { $_.DisplayName -ne $null } | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | ConvertTo-Json
      #This Powershell oneliner checks two registry locations for both 64-bit and 32-bit installed software, then filters out any values returned as "null".
      #Returns to JSON.
      register: installed

    - name: Return to JSON
      debug:
        msg: "{{ installed.stdout }}"
        #Prints the JSON output to stdout.