---
- name: Join Windows Machine to Active Directory
  hosts: all
  gather_facts: false  # Disable fact gathering for Windows hosts

 

  tasks:
    - name: Join the machine to AD
      win_domain_membership:
        dns_domain_name: "{{ ad_domain }}"
        domain_admin_user: "{{ ad_user }}"
        domain_admin_password: "{{ ad_password }}"
        state: "domain"
    
    - name: Restart the machine
      win_reboot:
      when: ansible_reboot_pending | bool

