- name: Install WinPEAS to Windows
  hosts: all
  gather_facts: false
  
  vars:
    github_url: "https://github.com/carlospolop/PEASS-ng/tree/master/winPEAS"

  tasks:
    - name: Install WINPEAS ns
      git:
        repo: "{{ github_url }}"
        dest: "."
  
    - name: Run PS1 script
      win_shell: "./winPEAS/winPEASps1/winPEAS.ps1"1
    

    
