- name: Add SSH public key to remote hosts
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Add the provided SSH public key to authorized keys
      ansible.builtin.authorized_key:
        user: root
        state: present
        key: "{{ ssh_public_key }}" 
